"""Initial migration

Revision ID: 02231d05796e
Revises: 
Create Date: 2026-06-25 11:02:36.460242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02231d05796e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unique_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_unique_code'), ['unique_code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'employee', name='userrole'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_organization_created_by_user', 'user', ['created_by'], ['id'])

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('temp_password', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)

    op.create_table('quotation_custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default_visible', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_custom_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_custom_field_organization_id'), ['organization_id'], unique=False)

    op.create_table('quotation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('number_prefix', sa.String(length=10), nullable=True),
    sa.Column('number_counter', sa.Integer(), nullable=True),
    sa.Column('number_format', sa.String(length=30), nullable=True),
    sa.Column('invoice_counter', sa.Integer(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('default_gst_rate', sa.Float(), nullable=True),
    sa.Column('default_sgst_rate', sa.Float(), nullable=True),
    sa.Column('default_cgst_rate', sa.Float(), nullable=True),
    sa.Column('default_igst_rate', sa.Float(), nullable=True),
    sa.Column('default_payment_terms', sa.Text(), nullable=True),
    sa.Column('default_delivery_terms', sa.Text(), nullable=True),
    sa.Column('default_notes', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_gstin', sa.String(length=15), nullable=True),
    sa.Column('company_pan', sa.String(length=10), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True),
    sa.Column('company_state', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=100), nullable=True),
    sa.Column('pdf_footer_text', sa.Text(), nullable=True),
    sa.Column('show_bank_details_on_pdf', sa.Boolean(), nullable=True),
    sa.Column('show_signature_on_pdf', sa.Boolean(), nullable=True),
    sa.Column('default_signature_path', sa.String(length=255), nullable=True),
    sa.Column('default_signature_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_settings_organization_id'), ['organization_id'], unique=True)

    op.create_table('quotation_term_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_term_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_term_group_organization_id'), ['organization_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_organization_id'), ['organization_id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other', name='leadsource'), server_default=sa.text("'Other'"), nullable=True),
    sa.Column('status', sa.Enum('New', 'Active', 'Inactive', 'Prospect', name='leadstatus'), server_default=sa.text("'New'"), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('gst_status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'organization_id', name='uq_lead_email_org'),
    sa.UniqueConstraint('phone_number', 'organization_id', name='uq_lead_phone_org')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_gst_number'), ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_updated_by'), ['updated_by'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sender_id'), ['sender_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('Glass', 'Hardware', 'Mirror', 'Aluminium', 'Accessories', 'Raw Material', 'Other', name='productcategory'), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Discontinued', name='productstatus'), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.Column('min_stock_alert', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_status'), ['status'], unique=False)

    op.create_table('quotation_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('term_title', sa.String(length=255), nullable=False),
    sa.Column('term_body', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['quotation_term_group.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_term_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_term_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other', name='leadsource'), server_default=sa.text("'Other'"), nullable=True),
    sa.Column('status', sa.Enum('New', 'Requirement Understood', 'Measurement Scheduled', 'Quotation Sent', 'Follow Up', 'Order Confirmed', 'In Production', 'Ready for Dispatch', 'Installation Scheduled', 'Installation Done', 'Completed', 'Cancelled', name='customerstatus'), server_default=sa.text("'New'"), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('gst_status', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'organization_id', name='uq_customer_email_org'),
    sa.UniqueConstraint('phone_number', 'organization_id', name='uq_customer_phone_org')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_gst_number'), ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_lead_id'), ['lead_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_updated_by'), ['updated_by'], unique=False)

    op.create_table('lead_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('Call', 'Meeting', 'Email', 'Note', 'Task', name='activitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_activity_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_organization_id'), ['organization_id'], unique=False)

    op.create_table('lead_follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('Call', 'Email', 'WhatsApp', 'Meeting', 'Site Visit', 'SMS', 'Other', name='followupmethod'), nullable=False),
    sa.Column('outcome', sa.Enum('Interested', 'Not Interested', 'Callback Requested', 'No Response', 'Meeting Scheduled', 'Converted', 'Other', name='followupoutcome'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=False),
    sa.Column('next_follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_follow_up', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_follow_up_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_follow_up_is_done'), ['is_done'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_follow_up_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_follow_up_organization_id'), ['organization_id'], unique=False)

    op.create_table('customer_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_document_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_document_organization_id'), ['organization_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Planning', 'In Progress', 'On Hold', 'Completed', 'Cancelled', name='projectstatus'), nullable=True),
    sa.Column('work_type', sa.Enum('Glass', 'Hardware', 'Mirror', name='projectworktype'), nullable=True),
    sa.Column('category', sa.Enum('Commercial', 'Residential', name='projectcategory'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_by'), ['updated_by'], unique=False)

    op.create_table('daily_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('work_category', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_task_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_project_id'), ['project_id'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Enum('Travel', 'Materials', 'Hardware', 'Salary', 'Site Expense', 'Office Supplies', 'Other', name='expensecategory'), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', 'Paid', name='expensestatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_path', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_project_id'), ['project_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('invoice_title', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('total_discount', sa.Float(), nullable=True),
    sa.Column('total_discount_type', sa.String(length=10), nullable=True),
    sa.Column('additional_charges', sa.Float(), nullable=True),
    sa.Column('additional_charges_taxable', sa.Boolean(), nullable=True),
    sa.Column('additional_charges_label', sa.String(length=100), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('igst', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_in_words', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Unpaid', 'Paid', 'Partially Paid', 'Cancelled', 'Overdue', name='invoicestatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_igst', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('signature_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_title', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.Enum('Quotation', 'Proforma Invoice', 'Sales Order', name='quotationdoctype'), nullable=True),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('valid_till_type', sa.String(length=10), nullable=True),
    sa.Column('valid_till_days', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('timeline', sa.String(length=255), nullable=True),
    sa.Column('amendment_no', sa.String(length=50), nullable=True),
    sa.Column('measurements', sa.String(length=255), nullable=True),
    sa.Column('quote_level', sa.String(length=255), nullable=True),
    sa.Column('sales_source', sa.String(length=255), nullable=True),
    sa.Column('delivery_terms', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.String(length=500), nullable=True),
    sa.Column('shop_drawings', sa.String(length=255), nullable=True),
    sa.Column('project_lead_name', sa.String(length=255), nullable=True),
    sa.Column('application', sa.String(length=255), nullable=True),
    sa.Column('manager_in_charge', sa.String(length=255), nullable=True),
    sa.Column('references', sa.String(length=255), nullable=True),
    sa.Column('delivery_tat', sa.String(length=255), nullable=True),
    sa.Column('mode_of_delivery', sa.String(length=255), nullable=True),
    sa.Column('unloading', sa.String(length=255), nullable=True),
    sa.Column('freight_unloading', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('total_discount', sa.Float(), nullable=True),
    sa.Column('total_discount_type', sa.String(length=10), nullable=True),
    sa.Column('additional_charges', sa.Float(), nullable=True),
    sa.Column('additional_charges_taxable', sa.Boolean(), nullable=True),
    sa.Column('additional_charges_label', sa.String(length=100), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('igst', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_in_words', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('advance_payment', sa.Float(), nullable=True),
    sa.Column('mode_of_payment', sa.String(length=100), nullable=True),
    sa.Column('balance_payment', sa.Float(), nullable=True),
    sa.Column('is_igst', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('signature_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Accepted', 'Rejected', name='quotationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotation_status'), ['status'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), server_default=sa.text("'Generic Task'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'In Progress', 'Completed', 'Cancelled', name='taskstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    op.create_table('crm_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('daily_task_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_task.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_document_daily_task_id'), ['daily_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_document_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_document_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_document_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_document_task_id'), ['task_id'], unique=False)

    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('formula_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('chargeable_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.String(length=10), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('quotation_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_attachment_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_custom_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['quotation_custom_field.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_custom_field_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_custom_field_value_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_custom_field_value_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('formula_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('chargeable_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.String(length=10), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('is_undefined_size', sa.Boolean(), nullable=True),
    sa.Column('is_all_selection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_item_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('sig_type', sa.String(length=10), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('pad_data', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_signature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_signature_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_tax_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_tax_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_tax_summary_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_term_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('custom_title', sa.String(length=255), nullable=True),
    sa.Column('custom_body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['quotation_term_group.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['quotation_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_term_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_term_link_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_term_link_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_term_link_term_id'), ['term_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS = 0;')
    with op.batch_alter_table('quotation_term_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_term_link_term_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_term_link_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_term_link_group_id'))

    op.drop_table('quotation_term_link')
    with op.batch_alter_table('quotation_tax_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_tax_summary_quotation_id'))

    op.drop_table('quotation_tax_summary')
    with op.batch_alter_table('quotation_signature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_signature_quotation_id'))

    op.drop_table('quotation_signature')
    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_item_quotation_id'))

    op.drop_table('quotation_item')
    with op.batch_alter_table('quotation_custom_field_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_custom_field_value_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_custom_field_value_field_id'))

    op.drop_table('quotation_custom_field_value')
    with op.batch_alter_table('quotation_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_attachment_quotation_id'))

    op.drop_table('quotation_attachment')
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))

    op.drop_table('invoice_item')
    with op.batch_alter_table('crm_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_document_task_id'))
        batch_op.drop_index(batch_op.f('ix_crm_document_project_id'))
        batch_op.drop_index(batch_op.f('ix_crm_document_organization_id'))
        batch_op.drop_index(batch_op.f('ix_crm_document_lead_id'))
        batch_op.drop_index(batch_op.f('ix_crm_document_daily_task_id'))

    op.drop_table('crm_document')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_organization_id'))
        batch_op.drop_index(batch_op.f('ix_task_lead_id'))
        batch_op.drop_index(batch_op.f('ix_task_created_by'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to'))

    op.drop_table('task')
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_status'))
        batch_op.drop_index(batch_op.f('ix_quotation_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotation_project_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_lead_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_customer_id'))

    op.drop_table('quotation')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_project_id'))
        batch_op.drop_index(batch_op.f('ix_expense_organization_id'))
        batch_op.drop_index(batch_op.f('ix_expense_employee_id'))

    op.drop_table('expense')
    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_daily_task_organization_id'))
        batch_op.drop_index(batch_op.f('ix_daily_task_employee_id'))

    op.drop_table('daily_task')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updated_by'))
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_organization_id'))
        batch_op.drop_index(batch_op.f('ix_project_customer_id'))
        batch_op.drop_index(batch_op.f('ix_project_created_by'))
        batch_op.drop_index(batch_op.f('ix_project_assigned_to'))

    op.drop_table('project')
    with op.batch_alter_table('customer_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_document_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_document_customer_id'))

    op.drop_table('customer_document')
    with op.batch_alter_table('lead_follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_follow_up_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_follow_up_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_follow_up_is_done'))
        batch_op.drop_index(batch_op.f('ix_lead_follow_up_created_by'))

    op.drop_table('lead_follow_up')
    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))

    op.drop_table('lead_activity')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_updated_by'))
        batch_op.drop_index(batch_op.f('ix_customer_status'))
        batch_op.drop_index(batch_op.f('ix_customer_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_lead_id'))
        batch_op.drop_index(batch_op.f('ix_customer_gst_number'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_created_by'))
        batch_op.drop_index(batch_op.f('ix_customer_assigned_to'))

    op.drop_table('customer')
    with op.batch_alter_table('quotation_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_term_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_term_group_id'))

    op.drop_table('quotation_term')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_status'))
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_organization_id'))

    op.drop_table('product')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_sender_id'))
        batch_op.drop_index(batch_op.f('ix_notification_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    op.drop_table('notification')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_gst_number'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))

    op.drop_table('lead')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('quotation_term_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_term_group_organization_id'))

    op.drop_table('quotation_term_group')
    with op.batch_alter_table('quotation_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_settings_organization_id'))

    op.drop_table('quotation_settings')
    with op.batch_alter_table('quotation_custom_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_custom_field_organization_id'))

    op.drop_table('quotation_custom_field')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))

    op.drop_table('employee')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))

    op.drop_table('organization')
    op.execute('SET FOREIGN_KEY_CHECKS = 1;')
    # ### end Alembic commands ###
