"""Quotation engine upgrade

Revision ID: 0ab209c5b492
Revises: 40ab81d65a32
Create Date: 2026-04-07 12:27:11.133530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ab209c5b492'
down_revision = '40ab81d65a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('doc_type', sa.Enum('Quotation', 'Proforma Invoice', 'Sales Order', name='quotationdoctype'), nullable=True))
        batch_op.add_column(sa.Column('valid_till_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('valid_till_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sales_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_terms', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('shop_drawings', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('project_lead_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('application', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('manager_in_charge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('references', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_tat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mode_of_delivery', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unloading', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('freight_unloading', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_discount_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('additional_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges_taxable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('igst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_in_words', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advance_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mode_of_payment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('balance_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_igst', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sgst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('igst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_undefined_size', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_all_selection', sa.Boolean(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    pass
