"""add structured activity fields

Revision ID: 0bec5ae49125
Revises: 5315bf44519e
Create Date: 2026-07-30 15:48:17.843848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bec5ae49125'
down_revision = '5315bf44519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('related_entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('related_entity_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('related_entity_id')
        batch_op.drop_column('related_entity_type')
        batch_op.drop_column('meta_data')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('field_name')

    # ### end Alembic commands ###
