"""Add Task table

Revision ID: 1600441ed58a
Revises: 389910c2da2e
Create Date: 2026-03-28 14:25:51.986108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1600441ed58a'
down_revision = '389910c2da2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_organization_id'), ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_organization_id'))
        batch_op.drop_index(batch_op.f('ix_task_lead_id'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to'))

    op.drop_table('task')
    # ### end Alembic commands ###
