"""add lead_comment table

Revision ID: 2c1cb23b3038
Revises: b1412964e8c7
Create Date: 2026-07-03 11:47:27.199676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c1cb23b3038'
down_revision = 'b1412964e8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_comment_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_comment_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_comment_organization_id'), ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_comment_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_comment_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_comment_created_by'))

    op.drop_table('lead_comment')
    # ### end Alembic commands ###
