"""add references to invoice and hsn_sac to invoice_item

Revision ID: 2c46adc1f857
Revises: d4e5f6a7b8c9
Create Date: 2026-08-11 14:47:04.400490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c46adc1f857'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_sac', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_column('hsn_sac')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('references')
    # ### end Alembic commands ###
