"""add_gst_fields

Revision ID: 2ce58844f663
Revises: 5ec725edcf69
Create Date: 2026-03-30 13:57:34.812446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ce58844f663'
down_revision = '5ec725edcf69'
branch_labels = None
depends_on = None


def upgrade():
    # Only add GST columns to customer
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('trade_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gst_status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_gst_number'), ['gst_number'], unique=False)

    # Only add GST columns to lead
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('trade_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gst_status', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_lead_gst_number'), ['gst_number'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('idx_user_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))
        batch_op.create_index(batch_op.f('unique_code'), ['unique_code'], unique=True)

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))
        batch_op.create_index(batch_op.f('idx_lead_activity_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_gst_number'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))
        batch_op.create_index(batch_op.f('idx_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=False,
               existing_server_default=sa.text("'New'"))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=False,
               existing_server_default=sa.text("'Other'"))
        batch_op.drop_column('gst_status')
        batch_op.drop_column('business_type')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('trade_name')
        batch_op.drop_column('gst_number')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_customer_gst_number'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_column('gst_status')
        batch_op.drop_column('business_type')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('trade_name')
        batch_op.drop_column('gst_number')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))
        batch_op.create_index(batch_op.f('idx_org_created'), ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_actor'), ['actor_id'], unique=False)

    # ### end Alembic commands ###
