"""Add Multi-Tenant Organization Support

Revision ID: 389910c2da2e
Revises: 965218b5d8a5
Create Date: 2026-03-28 10:41:48.679856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '389910c2da2e'
down_revision = '965218b5d8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unique_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_unique_code'), ['unique_code'], unique=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=True,
               existing_server_default=sa.text("'Other'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Requirement Understood', 'Measurement Scheduled', 'Quotation Sent', 'Follow Up', 'Order Confirmed', 'In Production', 'Ready for Dispatch', 'Installation Scheduled', 'Installation Done', 'Completed', 'Cancelled'),
               nullable=True,
               existing_server_default=sa.text("'New'"))
        batch_op.create_index(batch_op.f('ix_customer_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_updated_by'), ['updated_by'], unique=False)
        batch_op.create_foreign_key(None, 'employee', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_index(batch_op.f('ix_employee_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=True,
               existing_server_default=sa.text("'Other'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=True,
               existing_server_default=sa.text("'New'"))
        batch_op.create_index(batch_op.f('ix_lead_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_updated_by'), ['updated_by'], unique=False)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lead_activity_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=False,
               existing_server_default=sa.text("'New'"))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=False,
               existing_server_default=sa.text("'Other'"))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_updated_by'))
        batch_op.drop_index(batch_op.f('ix_customer_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_created_by'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Requirement Understood', 'Measurement Scheduled', 'Quotation Sent', 'Follow Up', 'Order Confirmed', 'In Production', 'Ready for Dispatch', 'Installation Scheduled', 'Installation Done', 'Completed', 'Cancelled'),
               nullable=False,
               existing_server_default=sa.text("'New'"))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=False,
               existing_server_default=sa.text("'Other'"))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))

    op.drop_table('organization')
    # ### end Alembic commands ###
