"""Added Quotation models

Revision ID: 425fe82c4342
Revises: f7f532e47cc5
Create Date: 2026-04-02 12:01:42.594987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '425fe82c4342'
down_revision = 'f7f532e47cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('amendment_no', sa.String(length=50), nullable=True),
    sa.Column('measurements', sa.String(length=255), nullable=True),
    sa.Column('quote_level', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Accepted', 'Rejected', name='quotationstatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotation_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotation_status'), ['status'], unique=False)

    op.create_table('quotation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('gst_percentage', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_item_quotation_id'), ['quotation_id'], unique=False)

    # (Other table index alterations removed to prevent foreign key errors)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # (Other table index alterations removed to prevent foreign key errors)

    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_item_quotation_id'))

    op.drop_table('quotation_item')
    with op.batch_alter_table('quotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_status'))
        batch_op.drop_index(batch_op.f('ix_quotation_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotation_project_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_lead_id'))
        batch_op.drop_index(batch_op.f('ix_quotation_customer_id'))

    op.drop_table('quotation')
    # ### end Alembic commands ###
