"""Added Project model

Revision ID: 505cd5c86b33
Revises: c04eef1c535e
Create Date: 2026-03-30 11:41:57.087362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '505cd5c86b33'
down_revision = 'c04eef1c535e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Planning', 'In Progress', 'On Hold', 'Completed', 'Cancelled', name='projectstatus'), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_updated_by'), ['updated_by'], unique=False)

    # Safely apply remaining index/constraint changes (may already exist in DB)

    try:
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
    except Exception:
        pass

    try:
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.create_unique_constraint(None, ['phone_number'])
    except Exception:
        pass

    try:
        with op.batch_alter_table('employee', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('user_id'))
    except Exception:
        pass

    try:
        with op.batch_alter_table('employee', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_employee_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)
            batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
    except Exception:
        pass

    try:
        with op.batch_alter_table('lead', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_lead_organization_id'))
    except Exception:
        pass

    try:
        with op.batch_alter_table('lead', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_lead_assigned_to'), ['assigned_to'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_created_by'), ['created_by'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_lead_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_updated_by'), ['updated_by'], unique=False)
    except Exception:
        pass

    try:
        with op.batch_alter_table('lead', schema=None) as batch_op:
            batch_op.create_unique_constraint(None, ['phone_number'])
    except Exception:
        pass

    try:
        with op.batch_alter_table('lead_activity', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_lead_activity_organization_id'))
    except Exception:
        pass

    try:
        with op.batch_alter_table('lead_activity', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_lead_activity_created_by'), ['created_by'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_activity_lead_id'), ['lead_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_lead_activity_organization_id'), ['organization_id'], unique=False)
    except Exception:
        pass

    try:
        with op.batch_alter_table('organization', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('unique_code'))
    except Exception:
        pass

    try:
        with op.batch_alter_table('organization', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_organization_unique_code'), ['unique_code'], unique=True)
            batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
    except Exception:
        pass

    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_user_organization_id'))
    except Exception:
        pass

    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('idx_user_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))
        batch_op.create_index(batch_op.f('unique_code'), ['unique_code'], unique=True)

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))
        batch_op.create_index(batch_op.f('idx_lead_activity_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))
        batch_op.create_index(batch_op.f('idx_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=False,
               existing_server_default=sa.text("'New'"))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=False,
               existing_server_default=sa.text("'Other'"))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_customer_email'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updated_by'))
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_organization_id'))
        batch_op.drop_index(batch_op.f('ix_project_customer_id'))
        batch_op.drop_index(batch_op.f('ix_project_created_by'))
        batch_op.drop_index(batch_op.f('ix_project_assigned_to'))

    op.drop_table('project')
    # ### end Alembic commands ###
