"""add temp_password to Employee

Revision ID: 9055d384a541
Revises: e2a3c4d5b6f7
Create Date: 2026-06-15 18:21:17.526073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9055d384a541'
down_revision = 'e2a3c4d5b6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_actor'))
        batch_op.drop_index(batch_op.f('idx_org_created'))
        batch_op.create_index(batch_op.f('ix_activity_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_task_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_index(batch_op.f('ix_employee_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=True,
               existing_server_default=sa.text("'Other'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=True,
               existing_server_default=sa.text("'New'"))
        batch_op.drop_index(batch_op.f('idx_lead_organization_id'))
        batch_op.create_index(batch_op.f('ix_lead_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_updated_by'), ['updated_by'], unique=False)

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lead_activity_organization_id'))
        batch_op.create_index(batch_op.f('ix_lead_activity_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activity_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_code'))
        batch_op.create_index(batch_op.f('ix_organization_unique_code'), ['unique_code'], unique=True)
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_organization_id'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('idx_user_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('quotation_item', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organization_unique_code'))
        batch_op.create_index(batch_op.f('unique_code'), ['unique_code'], unique=True)

    with op.batch_alter_table('lead_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activity_created_by'))
        batch_op.create_index(batch_op.f('idx_lead_activity_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_updated_by'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_created_by'))
        batch_op.drop_index(batch_op.f('ix_lead_assigned_to'))
        batch_op.create_index(batch_op.f('idx_lead_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('New', 'Active', 'Inactive', 'Prospect'),
               nullable=False,
               existing_server_default=sa.text("'New'"))
        batch_op.alter_column('source',
               existing_type=mysql.ENUM('Website', 'Google', 'Social Media', 'Referral', 'Walk-in', 'Other'),
               nullable=False,
               existing_server_default=sa.text("'Other'"))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_organization_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_task_project_id'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))
        batch_op.create_index(batch_op.f('idx_org_created'), ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_actor'), ['actor_id'], unique=False)

    # ### end Alembic commands ###
