"""add_task_activity_timeline

Revision ID: b1412964e8c7
Revises: 02231d05796e
Create Date: 2026-07-01 13:41:59.037309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1412964e8c7'
down_revision = '02231d05796e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('Call', 'WhatsApp', 'Email', 'Meeting', 'Comment', 'Follow Up', 'Payment', 'Update', name='taskactivitytype'), nullable=False),
    sa.Column('call_result', sa.Enum('Connected', 'No Answer', 'Busy', 'Switched Off', 'Wrong Number', 'Call Back Later', 'Rejected', 'Interested', 'Not Interested', name='callresult'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('next_follow_up_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_activity_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_activity_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_activity_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_activity_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('crm_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_activity_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_crm_document_task_activity_id'), ['task_activity_id'], unique=False)
        batch_op.create_foreign_key('fk_crm_document_task_activity_id', 'task_activity', ['task_activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_crm_document_task_activity_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_crm_document_task_activity_id'))
        batch_op.drop_column('task_activity_id')

    with op.batch_alter_table('task_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_activity_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_activity_organization_id'))
        batch_op.drop_index(batch_op.f('ix_task_activity_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_task_activity_employee_id'))
        batch_op.drop_index(batch_op.f('ix_task_activity_created_at'))

    op.drop_table('task_activity')
    # ### end Alembic commands ###
