"""Add Notification model

Revision ID: c7a429b6e679
Revises: eb08c902c7db
Create Date: 2026-04-14 10:45:41.602060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7a429b6e679'
down_revision = 'eb08c902c7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_sender_id'))
        batch_op.drop_index(batch_op.f('ix_notification_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    op.drop_table('notification')
    # ### end Alembic commands ###
