"""Advanced Invoice and InvoiceItem models

Revision ID: eb08c902c7db
Revises: d9adaab51e15
Create Date: 2026-04-13 15:17:14.168498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb08c902c7db'
down_revision = 'd9adaab51e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_discount_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('additional_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges_taxable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('additional_charges_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('igst', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_in_words', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_igst', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terms_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_label', sa.String(length=100), nullable=True))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('formula_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chargeable_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gst_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sgst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cgst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('igst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('total')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('igst_rate')
        batch_op.drop_column('cgst_rate')
        batch_op.drop_column('sgst_rate')
        batch_op.drop_column('gst_percentage')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('discount')
        batch_op.drop_column('unit')
        batch_op.drop_column('chargeable_quantity')
        batch_op.drop_column('formula_type')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('item_name')
        batch_op.drop_column('group_name')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('signature_label')
        batch_op.drop_column('terms_conditions')
        batch_op.drop_column('is_igst')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('total_in_words')
        batch_op.drop_column('igst')
        batch_op.drop_column('cgst')
        batch_op.drop_column('sgst')
        batch_op.drop_column('additional_charges_label')
        batch_op.drop_column('additional_charges_taxable')
        batch_op.drop_column('additional_charges')
        batch_op.drop_column('total_discount_type')
        batch_op.drop_column('total_discount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('invoice_title')
    # ### end Alembic commands ###
