"""Added Invoice and InvoiceItem models

Revision ID: f7f532e47cc5
Revises: 070f7e788f9b
Create Date: 2026-04-02 10:47:41.669997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f532e47cc5'
down_revision = '070f7e788f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Unpaid', 'Paid', 'Partially Paid', 'Cancelled', 'Overdue', name='invoicestatus'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)

    # Note: Removed index drops for existing tables (activity_log, user, etc.)
    # to avoid MySQL foreign key index constraint conflicts.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))

    op.drop_table('invoice_item')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    # ### end Alembic commands ###
